name: "Build and deploy to github nuget repository"
description: "Build procject and deploys nugetpackage to github repository"

inputs:
  project_path:
    description: "Path to nuget project that will be build and deployed"
    required: true
  version:
    description: "Version to be set on nuget package"   
    
env:
  PROJECT_PATH: ${{ inputs.project_path }}
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/outputnuget
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/WintDev/index.json'
  NUGET_VERSION_ENDING: ''
  GITHUB_REF: ${{ github.ref }}
  
runs:
  using: "composite"
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Branch
      id: get-branch
      run: |
        raw=$(git branch -r --contains ${{ env.GITHUB_REF }})
        branch=${raw/origin\/}
        echo ::set-output name=BRANCH::$branch
        
    - name: Set prefix
      if: ${{ steps.get-branch.outputs.BRANCH != 'main' }}
      run: |
        echo "NUGET_VERSION_ENDING=-beta" >> $GITHUB_ENV
        
    - name: "Test Echo"
      run: echo ${{ env.NUGET_VERSION_ENDING }}
      
