name: "Build and deploy to github nuget repository"
description: "Build procject and deploys nugetpackage to github repository"

inputs:
  project_path:
    description: "Path to nuget project that will be build and deployed"
    required: true
  version:
    description: "Version to be set on nuget package"   

env:
    PROJECT_PATH: ${{ inputs.project_path }}
    
runs:
  using: "composite"
      
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
     
    - name: 'Echo'
      run: echo ${{ env.PROJECT_PATH }}
