name: az-storage-upload
on:
  workflow_call:
    inputs:
      storage-account-name:
        description: 'The name of the azure storage account.'
        required: true
        type: string
      storage-container-name:
        description: 'The name of the storage container.'
        required: true
        type: string
      source:
        description: 'The path to the location of the contents to upload to the blob storage.'
        required: true
        type: string

    secrets:
      azure-credentials:
        description: 'The credentials to use to authenticate against azure.'
        required: true

jobs:
  ensure-storage-container:
    uses: WintDev/actions/.github/workflows/ensure-storage-container.yml@experimental
    with:
      storage-container-name: ${{ inputs.storage-container-name }}
    secrets: inherit

  blob_upload:
    name: 'upload data to azure blob storage'
    runs-on: ubuntu-latest
    steps:
      - name: 'az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: 'upload blob.'
        shell: bash
        run: |
          az storage blob upload-batch --account-name ${{ inputs.storage-account-name }} --container ${{ inputs.storage-container-name }} --source ${{ inputs.source }}