name: build-push-container
on:
  workflow_call:
    inputs:
      login-server:
        description: 'The name of the Azure Container Registry. Defaults to wintcontainer.azurecr.io'
        required: true
        type: string
        default: 'wintcontainer.azurecr.io'
      dockerfile:
        description: 'The location of the dockerfile to build relative to the repository root. The default value is the dockerfile located at the repository root.'
        required: true
        type: string
        default: 'dockerfile'
      container-name:
        description: 'The name of the container. If no name is provided, the repository environment variable value is used as the container name.'
        type: string
      tag:
        description: 'The tag for which the cotainer would be pushed to the ACR. If not specified, the tag will be calculated based on the ref.'
        type: string
      environment:
        description: 'The value that would be used as the enviroment environmet variable value. The default value is Production'
        required: true
        type: string
        default: 'Production'

    secrets:
      username:
        description: 'Container registry username.'
        required: true
      password:
        description: 'Container registry password'
        required: true
      nuget-read-pat:
        description: 'The Personal Access Token used to access the WintDev internal nuget feed when restoring.'
        required: true        

jobs:
  get_tag:
        name: Get Tag from ref
        uses: WintDev/actions/.github/workflows/get-container-tag.yml@v4

  push_container:
    name: BuildAndPush
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.login-server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      
      - name: Calculate Container name
        id: get_container_name
        run: |
          INPUT_CONTAINER_NAME=${{ inputs.container-name }}
          REPO=${{ github.repository }}
          NAME=${INPUT_CONTAINER_NAME:-REPO}
          CONTAINER_NAME='${{ inputs.login-server }}/${NAME}'
          echo "container_name=$CONTAINER_NAME" >> $GITHUB_OUTPUT

      - name: Calculate tag
        id: calculate_tag
        run: |
          REFTAG=${{ needs.get_tag.outputs.tag }}
          INPUT_TAG=${{ inputs.tag }}
          TAG=${INPUT_TAG:-REFTAG}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build . -f ${{ inputs.dockerfile }} -t '${{ steps.get_container_name.outputs.container_name }}:${{ steps.calculate_tag.outputs.tag }}' --build-arg 'WINTDEV_NUGET_ACCESSTOKEN=${{ secrets.nuget-read-pat }}' --build-arg 'ASPNETCORE_ENVIRONMENT=${{ inputs.environment }}'

      - name: Push
        run: |
          docker push '${{ steps.get_container_name.outputs.container_name }}:${{ steps.calculate_tag.outputs.tag }}'