name: get-container-tag
on:
  workflow_call:
    outputs:
      tag:
        description: "The container tag calculated using the current ref."
        value: ${{ jobs.calculate_tag.outputs.tag }}
jobs:
  calculate_tag:
    name: 'Calculate container tag'
    runs-on: ubuntu-latest
    env:
      TAG: 'latest'
    outputs:
      tag: ${{ steps.set_output.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion (v5.x)
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Tag Staging or Production Container
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        run: |
          echo "TAG=${{ steps.gitversion.outputs.SemVer }}" >> $GITHUB_ENV

      - name: Tag Feature container
        if: ${{ startsWith(github.ref, 'refs/heads/feature') || startsWith(github.ref, 'refs/heads/bugfix') || startsWith(github.ref, 'refs/heads/experimental') }}
        run: |
          echo "TAG=dev.${{ github.sha }}" >> $GITHUB_ENV

      - name: Set Tag Output Value
        id: set_output
        run: |
          echo "tag=${{ env.TAG }}" >> $GITHUB_OUTPUT