name: get-subscription-id
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the Azure Subscription. Defaults to Wint'
        type: string
        required: false
        default: 'Wint'
    secrets:
      azure-credentials:
        description: 'The credentials to use to authenticate against azure.'
        required: true

    outputs:
      id:
        description: "The container name calculated using the current ref (i.e. repository name)."
        value: ${{ jobs.get_subscription_id.outputs.id }}
jobs:
  get_subscription_id:
    name: 'Get Subscription ID'
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.get_id.outputs.id }}

    steps:
      - name: 'az login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: 'Get Subscription ID'
        id: get_id
        shell: bash
        run: |
          ID=$(az account show --subscription "${{ inputs.name }}" --query id -o tsv)
          echo "id=$ID" >> $GITHUB_OUTPUT